### ISSUE TITLE
Crashes when using YugabyteDB

### ISSUE THREAD

**Issue by carnei-ro** [prometheus-community/postgres_exporter#725]
**What did you do?**

Just run the exporter (basic config) connecting to YugabyteDB

**What did you expect to see?**

The metrics

**What did you see instead? Under which circumstances?**

Panic

YugabyteDB is returning `0.000000000 (Normal priority transaction)` at `setting` from `pg_settings`. It makes the function `normaliseUnit` crashes when trying to `ParseFloat`; 

|          name           |                  setting                  | coalesce |                                                         short_desc                                                         | vartype |
|-------------------------|-------------------------------------------|----------|----------------------------------------------------------------------------------------------------------------------------|---------|
| yb_transaction_priority | 0.000000000 (Normal priority transaction) |          | Gets the transaction priority used by the current active transaction in the session. If no transaction is active, return 0 | real |

As workaround I changed the query from `querySettings` to ignore this setting

```diff
-	query := "SELECT name, setting, COALESCE(unit, ''), short_desc, vartype FROM pg_settings WHERE vartype IN ('bool', 'integer', 'real') AND name != 'sync_commit_cancel_wait';"
+	query := "SELECT name, setting, COALESCE(unit, ''), short_desc, vartype FROM pg_settings WHERE vartype IN ('bool', 'integer', 'real') AND name NOT IN ('sync_commit_cancel_wait', 'yb_transaction_priority');"
```

**Environment**

Production

* postgres_exporter version:

`v0.11.1`

* PostgreSQL version:

`11.2.0`

* Logs:
```
ts=2022-11-28T13:14:51.893Z caller=collector.go:196 level=error msg="collector failed" name=database duration_seconds=0.241251568 err="sql: Scan error on column index 1, name \"pg_database_size\": converting NULL to int64 is unsupported"
panic: Error converting setting "yb_transaction_priority" value "0.000000000 (Normal priority transaction)" to float: strconv.ParseFloat: parsing "0.000000000 (Normal priority transaction)": invalid syntax

goroutine 39 [running]:
main.(*pgSetting).metric(0x40002fcff0, 0x40000a1c40?)
        /data/cmd/postgres_exporter/pg_setting.go:87 +0x294
main.querySettings(0x0?, 0x40000b53f0)
        /data/cmd/postgres_exporter/pg_setting.go:56 +0x244
main.(*Server).Scrape(0x40000b53f0, 0x400016a000?, 0xf0?)
        /data/cmd/postgres_exporter/server.go:121 +0xe8
main.(*Exporter).scrapeDSN(0x40000aa240, 0x0?, {0x400016a000, 0xbb})
        /data/cmd/postgres_exporter/datasource.go:116 +0x1a4
main.(*Exporter).scrape(0x40000aa240, 0x0?)
        /data/cmd/postgres_exporter/postgres_exporter.go:711 +0x1ac
main.(*Exporter).Collect(0x40000aa240, 0x4000047f58?)
        /data/cmd/postgres_exporter/postgres_exporter.go:600 +0x28
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:448 +0xe0
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:538 +0x8e0
```

**Comment by sysadmind** [comment]
Bad/non-numeric pg_settings values were hardened in #1252 (v0.19.0). Please retest on a current release; closing as likely resolved.
